---

- name: Install tools
  yum:
    name: '{{ item.name }}'
    state: present
    update_cache: yes
  with_items: '{{ tools_packages }}'

- name: Start yum-cron updates
  service:
    name: yum-cron
    state: started
    enabled: yes
