---

- name: Step 01. Update system
  include_tasks: update_system.yml

- name: Step 02. Install tools
  include_tasks: install_tools.yml

- name: Step 03. Disable SELinux
  include_tasks: disable_selinux.yml

- name: Step 04. Synchronize time
  include_tasks: synchronize_time.yml
