---

- name: Step 00. Create_ansible_user.yml
  include_tasks: create_ansible_user.yml

- name: Step 01. Update system
  include_tasks: update_system.yml

- name: Step 02. Install EPEL
  include_tasks: install_epel.yml

- name: Step 03. Install tools
  include_tasks: install_tools.yml

- name: Step 04. Set synchronize time
  include_tasks: set_synchronize_time.yml

- name: Step 05. Update system
  include_tasks: update_system.yml

#- name: Step 06. Reboot system
#  include_tasks: reboot_system.yml
