---

- name: Step 01. Update system
  include_tasks: update_system.yml

- name: Step 02. Install EPEL
  include_tasks: install_epel.yml

- name: Step 03. Install tools
  include_tasks: install_tools.yml

- name: Step 04. Disable IPV6
  include_tasks: disable_ipv6.yml

- name: Step 05. Disable SELinux
  include_tasks: disable_selinux.yml

- name: Step 06. Enable Iptables
  include_tasks: enable_iptables.yml

- name: Step 08. Set synchronize time
  include_tasks: set_synchronize_time.yml

- name: Step 09. Install fail2ban
  include_tasks: install_fail2ban.yml

- name: Step 10. Update system
  include_tasks: update_system.yml

