---

- name: Update and Upgrade all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Autoremove packages
  apt:
    autoremove: yes
- name: Autoclean packages
  apt:
    autoclean: yes
