---

sysctl_params:
  # Разрешение пересылки сетевых пакетов
  # между сетевыми интерфейсами в системе
  net.ipv4.ip_forward: 1
  # Внесение изменений в размеры буферов
  # для приема и отправки данных через сокеты
  net.core.rmem_default: 16777216
  net.core.rmem_max: 16777216
  net.core.wmem_default: 16777216
  net.core.wmem_max: 16777216
  net.ipv4.tcp_rmem: 4096 16777216  16777216
  net.ipv4.tcp_wmem: 4096 16777216  16777216
  # Включим защиту от «наводнения» syn пакетами
  net.ipv4.tcp_syncookies: 1
  # Запретим принимать ICMP редиректы:
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.default.accept_redirects: 0
  # Игнорируем широковещательные ICMP запросы:
  net.ipv4.icmp_echo_ignore_broadcasts: 1
  # Игнорируем пакеты в которых указан путь до источника:
  net.ipv4.conf.all.accept_source_route: 0
  # Укажем диапазон портов, которые разрешено использовать в качестве локальных.
  # По умолчанию этот диапазон достаточно мал,
  # и при высокой нагрузке вам их может просто не хватить:
  net.ipv4.ip_local_port_range: 16384    61000
  # Уменьшим время которое используется для сообщений о поддержке keep alive соединений:
  net.ipv4.tcp_keepalive_time: 1800
  # Уменьшим время до закрытия TCP-соединения.
  # Данный параметр стоит менять только на высоко нагруженных серверах?
  # net.ipv4.netfilter.ip_conntrack_tcp_timeout_established: 200000
  # Увеличиваем количество conntrack соединений.
  # Необходимо менять значение по умолчанию только на высоко нагруженных серверах.
  # net.ipv4.ip_conntrack_max: 64000000
  # Указываем время в секундах, в течении которого следует ожидать приема FIN до закрытия сокета:
  net.ipv4.tcp_fin_timeout: 30
  # Указываем количество пакетов проверки keepalive посылать, прежде чем TCP соединение будет закрыто:
  net.ipv4.tcp_keepalive_probes: 2
  # Указываем максимальное количество начальных SYN и SYN+ACK повторов
  # для установки TCP соединения. Данные параметры следует использовать с осторожностью
  # на плохих линиях связи т.к. есть вероятность, что TCP сессии никогда не будут установлены.
  net.ipv4.tcp_synack_retries: 3
  net.ipv4.tcp_syn_retries: 3
  ### Следующие параметры явно не влияют на производительность сетевой подсистемы.
  # В случае kernel panic производить перезагрузку роутера через 10 секунд.
  kernel.panic: 10
  # Отключаем tcp_timestamps, чтобы сетевые сканеры не могли узнать uptime роутера по его сетевым откликам:
  net.ipv4.tcp_timestamps: 0
  # Более подробно о параметрах sysctl,
  # влияющих на сетевую подсистему Linux,
  # можно прочитать на этих страницах
  # http://ipsysctl-tutorial.frozentux.net/chunkyhtml/tcpvariables.html.
  # https://redhat-club.org/2011/настройка-nat-в-rhel-centos-fedora
